const WEATHER_CODES = [
    { code: 0, description: "Clear sky" },
    { code: 1, description: "Mainly clear" },
    { code: 2, description: "Partly cloudy" },
    { code: 3, description: "Overcast" },
    { code: 45, description: "Fog" },
    { code: 48, description: "Fog" },
    { code: 51, description: "Drizzle" },
    { code: 53, description: "Drizzle" },
    { code: 55, description: "Drizzle" },
    { code: 56, description: "Freezing Drizzle" },
    { code: 57, description: "Freezing Drizzle" },
    { code: 61, description: "Rainy" },
    { code: 63, description: "Rainy" },
    { code: 65, description: "Rainyy" },
    { code: 66, description: "Freezing Rain" },
    { code: 67, description: "Freezing Rain" },
    { code: 71, description: "Snow fall" },
    { code: 73, description: "Snow fall" },
    { code: 75, description: "Snow fall" },
    { code: 77, description: "Snow grains" },
    { code: 80, description: "Rain showers" },
    { code: 81, description: "Rain showers" },
    { code: 82, description: "Rain showers" },
    { code: 85, description: "Snow showers" },
    { code: 86, description: "Snow showers" },
    { code: 95, description: "Thunderstorm" },
    { code: 96, description: "Thunderstorm with hail" },
    { code: 99, description: "Thunderstorm with hail" },
];

export default WEATHER_CODES;
